### ISSUE TITLE
Remember window position

### ISSUE THREAD

**Issue by Ryrynz** [Garteal/MPDN_Extensions#1]
Selecting remember window position' and then closing MPDN causes the playlist on next start to no longer match the height of MPDN's window. If you drag the window to it's minimum width and restart MPDN the window is now no longer snapped and sits on top of MPDN.

Remember window position should only remember if the window has been unsnapped or moved from it's default snapped position.

**Comment by Garteal** [comment]
Height issue is fixed now. 'Remember window position' is working alright at the moment. 
You should only use this if you want to position your window wherever you want and have it start up there the next time. If you want to keep your playlist snapped, then enable the snap option and it will stay snapped.

**Comment by Ryrynz** [comment]
Perhaps this could be changed to 'Keep snapped to player' and another option 'Scale with player'
since the playlist now defaults to snapping with MPDN. Also is it possible to grey out remember window position and remember window size options when 'Keep snapped to player' would be selected?

**Comment by Garteal** [comment]
Sure, that sounds good. Been thinking of doing that actually as it makes sense not to use both.

**Comment by Ryrynz** [comment]
Make sure it can stay snapped when MPDN's option 'Resize window to fit media' is enabled.
ATM the window detaches from the snapped position when this is enabled.

**Comment by Garteal** [comment]
Just checked, that seems to work fine here. It stays snapped.

**Comment by Ryrynz** [comment]
Got confused there. I forgot to mention that I had no options ticked in the playlist. The playlist window moves position rather than staying snapped. Just need to sort how how things behave when that happens without any playlist options being ticked.

**Comment by Ryrynz** [comment]
When the keep snapped option isn't enabled I think the snap should remain when MPDN's window changes size or moves automatically.

**Comment by Garteal** [comment]
How about we just have the "snap to player" option enabled by default and have it behave like you assume it will? Meaning off = no snapping and on = snapping. If we go with your suggestion we'll have the playlist snap even if you have it unticked (as it is right now). I think we should have a way to not snap at all. I'm sure there are some people that would appreciate it.

**Comment by Ryrynz** [comment]
Let's go with that.

**Comment by Garteal** [comment]
Can you check if everything is working as intended now?

**Comment by Ryrynz** [comment]
Select 'Remember window position' only, start MPDN (it starts snapped) then move the playlist window slightly and close the playlist. Reload the playlist, it appears at the top left corner of the screen.

**Comment by Garteal** [comment]
Can't reproduce. Can you try it again and see if it still happens? There was another bug that should be fixed now.

**Comment by Ryrynz** [comment]
Can no longer reproduce that. 

I've noticed that when MPDN resizes it's window (resize window to fit media) the playlist can end up in odd positions. Top middle, middle left, top right, based upon the resolution of the file. This is with no options ticked in the playlist. Also try resizing MPDN's window with the playlist snapped (default launch mode - no options ticked)  then move MPDN's window. The playlist will unsnap and overlay a little over MPDN's window. Do you think it should stay snapped in this situation? Not sure how you wished to proceed in these instances.

**Comment by Garteal** [comment]
I'm confused. With no options ticked, the playlist starts next to MPDN by default but it isn't snapped. Unless you meant with having "Snap to player" ticked, which should work properly. Aside from there being a gap here on Windows 10, I don't see any unsnapping or overlaying happening.

Also I think we should do something with the "Keep snapped" option as having that enabled basically just disallows you to move the window. Perhaps rename it or make it only tick-able when "Snap to player" is ticked?

**Comment by Ryrynz** [comment]
I refer to it as snapped because it looks identical to me on my system. The snapping option wasnt ticked. I'll provide more info hopefully which will allow this to reproduced. Yup grey keep snapped out and only allow it when snapping is ticked. I was thinking indenting it would help show that the snapping was a prerequisite for it.

**Comment by Ryrynz** [comment]
When you do move the 'Keep snapped' option, reckon it might be an idea to rename it to 'Stay snapped'

**Comment by Garteal** [comment]
Yep, had the same idea. Done this.

**Comment by Ryrynz** [comment]
Looks good. Everything seems to be working as expected, so I'm closing this.
