### ISSUE TITLE
Grey and strikeout not done when deleted file is clicked on

### ISSUE THREAD

**Issue by Ryrynz** [Garteal/MPDN_Extensions#1]
Add a file to the playlist and then delete the file. Attempt playback by double clicking on the playlist link. The file is not colored grey and striked out.

**Comment by Garteal** [comment]
Missed this use-case. I'll get this fixed.

**Comment by Garteal** [comment]
Fixed in 54c7a10da492450f05c7dfbba3e5b834d8cb2b58
