### ISSUE TITLE
Remember window width and height only remember on exit

### ISSUE THREAD

**Issue by Ryrynz** [Garteal/MPDN_Extensions#11]
If 'Remember window size' or 'Remember Windows position' are enabled and you close and reopen the playlist, it's displays at minimum width and height and starts that way regardless of the size the playlist is resized to. Only if MPDN is closed does it remember window width or height.

When this is not selected the playlist remembers it's previous size and position while MPDN is still loaded and the playlist is closed.

Do we want simply want 'Remember last window position' and 'Remember last window size' settings
so that the remembering functions of both current ticked and unticked options are combined?

**Comment by Garteal** [comment]
Nah they shouldn't be combined. It was really buggy but I've fixed some things. Right now, it's how should've been: remembering the position only will remember the position only and the size will be the MPDN height. Similarily for size, the position will be next to MPDN by default and the size to whatever you set it as.

**Comment by Garteal** [comment]
Should be good right?

**Comment by Ryrynz** [comment]
Everything seems pretty good on first test, will give it a final run through tomorrow.

**Comment by Ryrynz** [comment]
Haven't run into any issues, looking good.
