### ISSUE TITLE
Begin playback when file is added restarts playback

### ISSUE THREAD

**Issue by Ryrynz** [Garteal/MPDN_Extensions#13]
If begin playback when file is added is selected and you're currently playing files
adding more files will cause the currently playing file to stop and start playback of the first file in the playlist. Thoughts on adding something like 'Not while playing'?

**Comment by zachsaw** [comment]
I actually prefer it to auto play only when the playlist is empty. Try not to add too many options as it becomes hard to maintain and most users would simply use the default behaviour anyway.

**Comment by Ryrynz** [comment]
Yeah, I was thinking the exact same thing with regards to options. Perhaps just change the default behavior.

**Comment by Garteal** [comment]
Fixing it to behave like this: if you add one file (a time) it'll play the last file (thus the one you've added) in the playlist. If you add multiple files, it'll start at the first file. Sound good?

**Comment by Ryrynz** [comment]
If you're playing the first file and you add multiple files then it restarts playback of the same first file.
Might it be worth having an exception in that case?
This will remain rather crude unless there's an option, but if you guys are happy with the current implementation then all good.

**Comment by Garteal** [comment]
Yeah I'm not handling that case. I was thinking about it but forgot to reply here.
I can handle that and have it play the first file (from the group of files you've added). That sound good?

**Comment by Ryrynz** [comment]
That sounds more in line with the other use case of adding a single file, so yeah.
What about Zach's preference for only auto playing when the playlist is empty?

**Comment by Garteal** [comment]
I don't know. We'll have to change the wording then if we're to change the behavior of it now.
I'll probably add some sort of description area to the option dialog to prevent us from having to make up a good (short) name.

Also in case it wasn't known: you can add to the playlist without it starting playback or you can drag and drop (multiple) files (or folder(s)) to MPDN and have it play the file(s). I think that whoever suggested the option wanted to have the same behavior as above for the playlist.

**Comment by Ryrynz** [comment]
Everything appears to be working fine.
