### ISSUE TITLE
Title and full path columns don't change to their minimum size on playlist resize

### ISSUE THREAD

**Issue by Ryrynz** [Garteal/MPDN_Extensions#13]
Bring in the playlist window so it has minimum width, Skip chapters and end chapters move to double height rather than staying on a single line. Once they are manually made their minimum size however they then always reduce down to that size when the window is brought back to minimum width.

**Comment by Garteal** [comment]
I'll have to add an option or something for remembering the column positions, etc.
Right now they'll always be saved and set to what was saved.
