### ISSUE TITLE
Column titles should be displayed by default using a single line

### ISSUE THREAD

**Issue by Ryrynz** [Garteal/MPDN_Extensions#14]
Ideally I think the titles should be displayed like this by default.

http://i.imgur.com/tOO745L.jpg

**Comment by Garteal** [comment]
They are already on a single line aren't they? If you mean making some of em smaller and stuff then yeah, I think we're almost on to doing that.

**Comment by Ryrynz** [comment]
Nope. I'm seeing Skip Chapters taking up two lines. (I've unticked all settings and closed MPDN)

**Comment by Garteal** [comment]
What's your resolution? I'm guessing that due to your small resolution it's scaling the playlist to the point it takes up two lines. Everything is still good here at 1080p.

**Comment by Garteal** [comment]
This is fixed now. Should work good again.

**Comment by Ryrynz** [comment]
Confirm fixed.
