### ISSUE TITLE
*Feature* When a file is in the playlist on load, activate play button.

### ISSUE THREAD

**Issue by Ryrynz** [Garteal/MPDN_Extensions#15]
Spoke about this some time ago with Zach. If a file is in the playlist on load (or maybe even if it isn't ie as soon as it's added) then activate the play button so that the file can be played with a single click via MPDN.

**Comment by Garteal** [comment]
Yep I remember this. Implemented this now.

**Comment by Garteal** [comment]
Want to mention it'll only queue a file if you are not playing a file or have a file paused.

**Comment by Ryrynz** [comment]
As per our discussion, we'll need to see if Zach can avoid having the first frame and the title displayed in the OSD which currently occurs.
