### ISSUE TITLE
Allow multiple folders to be selected using the add folder function

### ISSUE THREAD

**Issue by Ryrynz** [Garteal/MPDN_Extensions#15]
Currently you can only add one folder. However with the add files function you can currently select more than one folder which opens up the second to last selected folder.

Ideally if it's possible do not allow the user to be able to select more than one directory, but still of course allow multiple files to be selected.

**Comment by Garteal** [comment]
Not possible using the default dialogs. Will have to create a custom dialog for it, but that will probably introduce more problems than it's worth.
