### ISSUE TITLE
When entering player options closing the playlist also minimizes MPDN

### ISSUE THREAD

**Issue by Ryrynz** [Garteal/MPDN_Extensions#16]
Go into the playlist options via the icon, leave the options (save or don't save it doesn't matter)
and then close the playlist window straight after, MPDN's window will minimize.

Using MPDN's menu option View -> Playlist before closing the playlist window prevents MPDN's window from minimizing when the playlist's window closes.

**Comment by Garteal** [comment]
Interesting... managed to reproduce it before 27fc3151af7f. Now it doesn't minimize. Can you check if it still happens for you?

**Comment by Ryrynz** [comment]
Still happens. I deleted the playlist config file for a fresh start.

**Comment by Garteal** [comment]
Hmm still no go here. MPDN does lose focus, so I'll atleast force focus back to it I guess and see if that'll help.

**Comment by Garteal** [comment]
There. Should focus on MPDN now once you follow your steps.

**Comment by Ryrynz** [comment]
Confirmed Fixed.
