### ISSUE TITLE
Playlist does not snap

### ISSUE THREAD

**Issue by Ryrynz** [Garteal/MPDN_Extensions#2]
Select 'Remember window position', 'Remember window size' & 'Snap and scale'
Resize the playlist to it's minimum width & restart MPDN. The playlist's width is now I believe it's
default width & It's also not snapped. Entering the options and leaving the options will make
the playlist snap.

**Comment by Garteal** [comment]
Should be fixed. Ignore the multiple referencing. Messed up a bit :disappointed:
