### ISSUE TITLE
Close Button in Config Regex close the whole Configuration Panel

### ISSUE THREAD

**Issue by Belphemur** [Garteal/MPDN_Extensions#20]
Hello @Garteal ,

When playing with the Extension, I discover this bug. The Close button in "Configure regex" close the whole Configuration of the Extension. And In case I didn't click save/apply, all change are then lost.

**Comment by Garteal** [comment]
Thanks for opening this, I forgot about "close" closing down the settings window as well. Do we want the "close" button to save (behind the scenes) as well?

**Comment by Belphemur** [comment]
Yes, I think that would be perfect if it saves also.

On another matter, I thought I'd be nice to have a new entry in the Window menu for Playlist to be able to hide/show it easily. @zachsaw added that possibility couple of version of MPDN ago. I used it to add the "Check for Updates..." in the Help Menu.

**Comment by Garteal** [comment]
> Yes, I think that would be perfect if it saves also.

Done, I've changed the "Apply" button to a "Clear" button though if someone wants to get rid of everything at once for convenience.

> On another matter, I thought I'd be nice to have a new entry in the Window menu for Playlist to be able to hide/show it easily.

Well we have a way to show/hide the playlist already. It's in the View menu.

**Comment by Belphemur** [comment]
You are completely right ... I wonder how I missed it. My bad.

Thanks for the bugfix.

Github tips with issue: When you are committing something related to an issue you can link to it by adding #ISSUE_NUMBER like #20 
And if you do like this: "Fixes #20" github will close also the issue automatically ;)
