### ISSUE TITLE
Error with corrupted file

### ISSUE THREAD

**Issue by Ryrynz** [Garteal/MPDN_Extensions#23]
Having a single corrupted file in the playlist throws up a 'Object reference not set to an instance of an object' error. This error does not occur when another file which is not corrupted is also in the playlist in the next position.

**Comment by Garteal** [comment]
I think this should be fixed with aebae777e346b5db5d99daa0bc382adffb5308c5. Can you verify?

**Comment by Ryrynz** [comment]
Verified fixed.
