### ISSUE TITLE
Also getting object reference not set to an instance of an object error when show playlist on startup is enabled.

### ISSUE THREAD

**Issue by Ryrynz** [Garteal/MPDN_Extensions#24]
Done this with a fresh profile. Simply ticking this option causes the error to occur.
If the option is not ticked and I launch the playlist manually there's no error.

**Comment by zachsaw** [comment]
Garteal has fixed this and I'll be doing a .1 release soon.

**Comment by Ryrynz** [comment]
Ah that was the bug you guys were talking about, sweet as.
