### ISSUE TITLE
String not recognized as a valid boolean

### ISSUE THREAD

**Issue by Ryrynz** [Garteal/MPDN_Extensions#25]
Since doom9 sucks and I can't PM, try enabling Scale with player on your latest dev build.

**Comment by Ryrynz** [comment]
BTW at least on 7 and 10 the snapping is fine, can test 8 later today.

**Comment by zachsaw** [comment]
I enabled scale with player - no issues here...

**Comment by Garteal** [comment]
Closing because I too couldn't reproduce.
