### ISSUE TITLE
Previous track in playlist disappears briefly.

### ISSUE THREAD

**Issue by Ryrynz** [Garteal/MPDN_Extensions#26]
When 'Play next file in folder' is enabled when the playlist refreshes the previously played file disappears briefly when there is more than one file in the playlist.

**Comment by Garteal** [comment]
Is this still happening? I've tried to reproduce this and have two files in my playlist with "Play next file in folder" enabled and when playback ends for both files I'm not seeing any entry disappear.

**Comment by Ryrynz** [comment]
Yeah, I can still reproduce this. Add two files, play the second file and when the third one appends the second one will briefly disappear. And it'll also happen on the third file when the fourth appends to the playlist and so on. This will happen regardless of whether the playlist has focus or not.

**Comment by Garteal** [comment]
Are you playing said files from your network HDD?

**Comment by Ryrynz** [comment]
I tried some local files too same thing, also tried my HTPC too, does it there as well.

**Comment by Garteal** [comment]
Oh, I've managed to reproduce it. It only seems to happen with the default theme (or was only noticeable on it I should say). Going to see if I can find out what's causing it.

Edit: Should be fixed now.
