### ISSUE TITLE
Playlist disappears when minimized

### ISSUE THREAD

**Issue by Ryrynz** [Garteal/MPDN_Extensions#3]
Minimize the playlist and then minimize MPDN and bring MPDN back from minimized state.
The playlist has now disappeared but is still shown in the taskbar.
View playlist won't bring it back, you have to close MPDN and reload.

**Comment by Garteal** [comment]
Fixed in 54c7a10da492450f05c7dfbba3e5b834d8cb2b58 and 8c88842435b9b8e573c778f5b05ea066e8f65128.
