### ISSUE TITLE
Add folders first

### ISSUE THREAD

**Issue by Ryrynz** [Garteal/MPDN_Extensions#3]
ATM when files are added to the playlist via the add folder icon the files are sorted alphabetically regardless of whether they're in a directory or not. I'd like to see an option to add folders first (sorted alphabetically also) so it matches up with what's typically seen in Windows Explorer.

**Comment by Garteal** [comment]
Could you be a little more specific?
I've added a folder (with a bunch of subfolders in them) and everything shows up perfectly with _1. Death Note/Death Note 01.mkv_ coming before _Code Geass/Code Geass 01.mkv_

Are you referring to having subfolders appearing first in the playlist and then the files in the actual folder?

**Comment by Ryrynz** [comment]
http://i.imgur.com/VL3PxlM.jpg

Notice how the folders view first in Explorer but are listed alphabetically in the playlist after having dragged this folder into it.

**Comment by Garteal** [comment]
Alright cool. Copied your structure since all of mine (organized) worked good. I'll try to get it fixed.

**Comment by Garteal** [comment]
Made some changes. It's not entirely what I want yet, but let me know if it does what you were thinking.

**Comment by Ryrynz** [comment]
Not quite right yet.

http://i.imgur.com/pbKuwDl.jpg

Folders are on now the bottom and 'The Gift' which was first as it should be is now last.

**Comment by Garteal** [comment]
I made some changes to this in the previous commit. It's actually how I want atm, but I'm not sure if it'll work properly in all cases yet. It's basically what you want, but in reverse. First it displays what's in the folders, then the subfolders' files get displayed.

Unfortunately sorting won't sort properly since it doesn't seem to work for some reason and I'll have to look into it further to get it fixed.

**Comment by Ryrynz** [comment]
As above with 'The Gift',  if I add via the 'add files' icon then titles that start with ' are listed first.
If I use the add directory icon those same files are last (just before the subfolders)

Sorting the subfolders to the top ain't a big deal for now, but the sorting should be consistent for the files at least.

**Comment by Garteal** [comment]
Just realized that's not a straight apostrophe. Using a straight apostrophe will place it right before The_Raven. If I'm not mistaken it's one of the ’ apostrophes. Using those places it first like in your screeny. Anyway working on fixing the issue, stay tuned!

**Comment by Garteal** [comment]
Could you do some testing here? Everything should be consistent and sorting properly (on directory first), with the exception of it being the reverse of your request.

**Comment by Ryrynz** [comment]
Yup, everything looked good here too, will do a final check tomorrow.

**Comment by Ryrynz** [comment]
No issues that I can see. There could be an option to display directories first in the general options if you wanted to add that.
