### ISSUE TITLE
Error with 'close player after playback' enabled in fullscreen.

### ISSUE THREAD

**Issue by Ryrynz** [Garteal/MPDN_Extensions#4]
I get the following error when in fullscreen, either windowed or FSE when 'close player player after playback' is enabled.

Object reference not set to an instance of an object

Cannot access a disposed object. Object name 'video track bar'

If in non fullscreen windowed mode the player closes successfully.

**Comment by Garteal** [comment]
Reproduced this... pretty sure it used to work before though. I'll try to figure out where it goes wrong.
Good catch.

**Comment by Garteal** [comment]
This has been fixed.
