### ISSUE TITLE
Strike out previous played file

### ISSUE THREAD

**Issue by Ryrynz** [Garteal/MPDN_Extensions#6]
This option has disappeared from the dev branch, also in the current MPDN build this is not striking out the played items.

This could be renamed to 'Remember played files'

**Comment by Garteal** [comment]
That option has replaced with "Remember playlist" which remembers any n of files.
I remember your strike out request yes. We'll have to put that in an option though.

**Comment by Ryrynz** [comment]
That's right.. the wording that caught me out there.

Missing files are already given a strikethrough and colored light grey, so perhaps I could rename this
issue to "Grey out previously played files"

I'd recommend a darker grey color than the missing files, I remember we lightly touched on how the files would be determined as having been played. Whether it's just the result of finishing the file or playing back x amount of time and finishing the file.

**Comment by Garteal** [comment]
I'll work on the striking after release.

**Comment by Ryrynz** [comment]
Why are your thoughts on potentially allowing the removal of files from the playlist as an option alongside striking or greying out?

**Comment by Garteal** [comment]
So we'll have some checkboxes for that I guess.

In the "After playback" group:
- [ ] Strikeout file
- [ ] Remove file

Nvm, I'll just use a checkbox, but disallow checking both.

Atm I have it count as played whenever you open up something, which seems fine enough atm, but for the removal of the files, do you want to have em removed when it only completes playback or also whenever you switch files manually?

**Comment by Ryrynz** [comment]
Do another drop down box. Also could you add Grey out file?

Only do it after it completes.

**Comment by Garteal** [comment]
Oh yeah, right that's probably better. After it completes for both?

**Comment by Ryrynz** [comment]
Well, I thought when people went to the next file using that it was basically skipping that file
so I wouldn't mark is as completed, but up to you!

**Comment by Garteal** [comment]
Atm I only have the striking increase the playcount when you open the media immediately as it's only a cosmetic change.

**Comment by Ryrynz** [comment]
No issues here, all working well.
