### ISSUE TITLE
Change MPDN's view -> playlist as a tick selection

### ISSUE THREAD

**Issue by Ryrynz** [Garteal/MPDN_Extensions#9]
This way the playlist can be closed via MPDN. Got the go ahead from Zach.

**Comment by Garteal** [comment]
This is kinda done already atm without it having its radiobutton. Clicking on the option or using the keyboard shortcut will toggle the playlist.

**Comment by Ryrynz** [comment]
Should the playlist ideally have the focus once it's been launched?
As it stands if I CTRL-ALT-P to close and then use it again to open I can't continue to use that shortcut. Can the playlist be allowed to use MPDN's keyboard shortcuts when it has focus?

**Comment by Garteal** [comment]
Ah nice catch. As for having focus, why not? If you launch it you might as well give it the focus. As for the shortcuts while it's focused, I'll see if I can fix that.

**Comment by Ryrynz** [comment]
Working nicely. Just wondering, there's a closing animation played when the mouse is hovering on the playlist which doesn't occur otherwise (the playlist just disappears if the mouse cursor is on MPDN) is that normal?

**Comment by Garteal** [comment]
Yep this is normal. It happens because the opacity of the playlist gets lowered when you're not hovering over it and by default (blame Microsoft) it doesn't play the closing animation.

**Comment by zachsaw** [comment]
I've made the playlist form remain fully opaque when it's active regardless of whether the mouse is hovering over it. It makes it easier to see when navigating the playlist via keyboard. It should also fix the problem you mentioned Ryan.

**Comment by zachsaw** [comment]
Oh and I've made the view playlist menu item ticked when the playlist form is open.

**Comment by Ryrynz** [comment]
Good stuff, thanks.

**Comment by Ryrynz** [comment]
The playlist isn't staying opaque when mouse it hovering over it, and the playlist window is still given focus when alt-tabbing.

**Comment by zachsaw** [comment]
There's nothing that can be done with playlist window given focus when alt-tabbing - making MPDN the owner of the playlist form causes Windows to activate the top-most in the Z order when you alt-tab. If we don't make MPDN the owner, the playlist form can end up behind MPDN's window.

Mouse over works fine for me.

**Comment by Ryrynz** [comment]
Done a complete fresh install, mouse over is still turning the window solid. This is on W7. Will check it out on the W8.1 system.

**Comment by zachsaw** [comment]
Mouse over is supposed to turn it solid (opaque). When you move your mouse away from it, it'll still stay opaque until it's no longer has focus (e.g. activate MPDN window).

**Comment by Ryrynz** [comment]
Okay. ATM if I have focus on MPDN, the playlist is semi transparent. If I move the mouse over the playlist it it becomes opaque, if I move the mouse off the playlist then it's turns semi transparent again.

This is also how it's functioning on my W8.1 system.

Would it be worth the playlist having something like: if focus has not been given to it by mouse click then provide focus back on MPDN? That would get around the focus issue wouldn't it?

**Comment by Garteal** [comment]
Thanks for taking the time to make changes and refactoring in that mess Zachs. Really got to clean things up.

As for the hover behavior, if you hover your mouse over the playlist window, it'll become opaque. If you don't hover over it, it'll turn semi-transparent. It has been like that since the beginning.

With Zachs' changes the playlist window won't turn transparent anymore when it has focus and you move your mouse away from it. That's what he meant, not that it will stay opaque when you hover over it when it doesn't have focus.

> Would it be worth the playlist having something like: if focus has not been given to it by mouse click then provide focus back on MPDN? That would get around the focus issue wouldn't it?

Will have to implement it and see how it works.
